services:
  pg_mori:
    image: postgres:17.0
    container_name: pg_mori
    env_file:
      - .env
    volumes:
      - ./data_mori/:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5434:5432"
    networks:
      - mori_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  pg_mori:
    driver: local

networks:
  mori_db:
    name: mori_db
    external: true
